DROP TABLE IF EXISTS STORMALF.COUNTRY;
CREATE TABLE STORMALF.COUNTRY ( 
	COUNID CHAR(3) CCSID 297 NOT NULL DEFAULT '' , 
	COUNDE CHAR(30) CCSID 297 NOT NULL DEFAULT '' , 
	PRIMARY KEY( COUNID ) )   
	  
	RCDFMT FCOUN      ; 
  
LABEL ON TABLE STORMALF.COUNTRY 
	IS 'Country file' ; 
  
GRANT DELETE , INSERT , SELECT , UPDATE   
ON STORMALF.COUNTRY TO PUBLIC ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON STORMALF.COUNTRY TO STORMALF WITH GRANT OPTION ; 

INSERT INTO STORMALF.COUNTRY (COUNID,COUNDE) VALUES
	 ('BEL','BELGIUM                      '),
     ('FRA','FRANCE                       '),
     ('USA','UNITED STATES OF AMERICA     ');     